### ISSUE TITLE
Not used import in the generated code when using Scala 3.5.0

### ISSUE THREAD

**Issue by 2m** [indoorvivants/snapshot-testing#11]
Hi! After upgrading Scala to 3.5.0 I am getting unused import warning on the generated MUnit integration code.

```scala
[warn] -- Warning: /home/runner/work/rpimon/rpimon/target/scala-3.5.0/src_managed/test/MUnitIntegration.scala:20:35 
[warn] 20 |import com.indoorvivants.snapshots._
[warn]    |                                   ^
[warn]    |                                   unused import
```

It is coming from the following line: https://github.com/indoorvivants/snapshot-testing/blob/main/modules/snapshots-buildtime/src/main/resources/MunitSnapshotsIntegration.scala#L20

Looks like this import is safe to be removed.

**Comment by keynmol** [comment]
Thanks, should be fixed in 0.0.8!
