### ISSUE TITLE
difflib moved since munit 1.0.0-RC1

### ISSUE THREAD

**Issue by 2m** [indoorvivants/snapshot-testing#9]
Thanks for this great library! :) Having stayed at the python world for a while, I certainly miss snapshot testing in Scala.

While trying it out, I noticed that the code generated by the library does not compile after the changes made in munit 1.0.0-RC1: https://github.com/scalameta/munit/pull/756

```
[error] -- [E008] Not Found Error: /Users/martynas/projects/rpi-mon/target/scala-3.4.2/src_managed/test/MUnitIntegration.scala:21:22 
[error] 21 |import munit.internal.difflib.Diffs
[error]    |       ^^^^^^^^^^^^^^^^^^^^^^
```

A workaround is to use munit `1.0.0-M12` for now.

**Comment by keynmol** [comment]
Oof, thanks.

I've released 0.0.7 which should rectify this.
